name: Release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.sys.os }} 
    strategy:
      matrix:
        sys: 
          - { os: windows-latest, shell: pwsh }
          - { os: ubuntu-latest,  shell: bash }

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Dependencies
      if: ${{ matrix.sys.os == 'ubuntu-latest' }}
      run: sudo apt update && sudo apt install xorg-dev zenity

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Release
      uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
      with:
        name: ${{ github.ref }}
        tag: ${{ github.ref }}
        artifacts: build/wrench_*.zip
        allowUpdates: false
        draft: true
        omitBodyDuringUpdate: false
        omitDraftDuringUpdate: false
        omitNameDuringUpdate: false
        omitPrereleaseDuringUpdate: false
        prerelease: true
        replacesArtifacts: false
        skipIfReleaseExists: true
